sample_string="i am in all lower case"
print(sample_string.lower())
print(sample_string.upper())
print(sample_string.upper().isalpha())
print("THIRU".isupper())
print("THIRU".islower())
print("thiru".isupper())
print("thiru".islower())
print("A100".isupper())
print("a100".islower())
print("100".isdecimal())
print("100.101".isdecimal())
print("100".isnumeric())
print("100.101".isnumeric())
print("100".isdigit())
print(sample_string.title())
print("Am I start with AM".startswith("Am"))
print("Am I start with AM".startswith("am"))