sample_string="i am in all lower case"
print(sample_string.lower())
print(sample_string.upper())
print(sample_string.upper().isalpha())
print("THIRU".isupper())
print("THIRU".islower())
print("thiru".isupper())
print("thiru".islower())
print("A100".isupper())
print("a100".islower())
print("100".isdecimal())
print("100.101".isdecimal())
print("100".isnumeric())
print("100.101".isnumeric())
print("100".isdigit())
print(sample_string.title())
print("Am I start with AM".startswith("Am"))
print("Am I start with AM".startswith("am"))

mixed_case="A Song of Ice and Fire"
print(mixed_case)
print(mixed_case.isupper())
print(mixed_case.islower())
print(mixed_case.upper())
print(mixed_case.lower())
print(mixed_case.title())
title_case=mixed_case.title()
print(title_case)
mixed_case_starts=mixed_case.startswith("A")
print(mixed_case_starts)
mixed_case_ends=mixed_case.endswith("e")
print(mixed_case_ends)
wrds=mixed_case.split()
print(wrds[0])
print(" JOINED WITH ".join(wrds))